// Report lifecycle, untrusted Markdown and asynchronous session isolation.
'use strict';
const assert=require('assert'),fs=require('fs'),vm=require('vm');
const html=fs.readFileSync('dist/index.html','utf8'),elements=new Map();
function element(id){
  assert(html.includes(`id="${id}"`)||/^agent(Request|Tool)/.test(id),`Missing element ${id}`);
  if(!elements.has(id))elements.set(id,{id,value:'',textContent:'',innerHTML:'',hidden:false,disabled:false,open:false,listeners:{},setAttribute(k,v){this[k]=v;},scrollHeight:0,scrollTop:0,clientHeight:0,addEventListener(k,fn){this.listeners[k]=fn;},insertAdjacentHTML(_,text){this.innerHTML+=text;},showModal(){this.open=true;},close(){this.open=false;this.listeners.close?.();},focus(){}});
  return elements.get(id);
}
const record='b'.repeat(32),id='a'.repeat(32),calls=[];
const streams=[];
const suggestionButtons=Array.from({length:3},()=>({dataset:{},textContent:'',disabled:false,addEventListener(){}}));
let sessions=[],messages=[],hold=null,settings={model:'test',endpoint:'http://model.test'},failure=null,download=null;
const session={id,title:'空间消耗总报告',report_scope:'container',status:'completed',snapshot_id:record,model:'test',created_at:1,updated_at:2};
const sandbox={apiURL:path=>path,EventSource:class{constructor(url){this.url=url;this.listeners={};streams.push(this);}addEventListener(k,f){this.listeners[k]=f;}close(){this.closed=true;}},console,window:{},$:element,platform:{user:{role:'admin'},loaded:record,followLatest:true},snapshot:{revision:7,host:'host',finished_at:'2026-09-14'},document:{querySelectorAll:selector=>selector==='[data-agent-question]'?suggestionButtons:[],createElement:()=>({click(){}})},URL:{createObjectURL(blob){download=blob;return 'blob:test';},revokeObjectURL(){}},Blob,setTimeout:()=>1,clearTimeout(){},dateTime:String,showPage(){},esc:value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),api:async(path,options={})=>{
  calls.push({path,options});if(hold&&hold.path===path)return new Promise(resolve=>{hold.resolve=resolve;});
  if(failure&&path===failure.path)throw Error(failure.message);
  if(path==='/api/agent/settings')return {value:settings};
  if(path==='/api/agent/sessions')return {sessions:[...sessions]};
  if(path==='/api/agent/reports'){
    const source=JSON.parse(options.body);assert.equal(source.snapshot_id,record);assert.equal(source.revision,7);assert(['host','container'].includes(source.scope));assert.equal(source.concurrency,source.scope==='host'?5:3);
    session.report_scope=source.scope;sessions=[{...session}];
    messages=[{id:1,role:'user',content:'server report request'},{id:2,role:'tool_start',tool_name:'scan_directory',content:JSON.stringify({call_id:'c',arguments:'{"path":"/data/<unsafe>"}'})},{id:3,role:'assistant',created_at:3,content:'# 总报告\n\n| 路径 | 大小 |\n| --- | --- |\n| `/data` | **1 GiB** |\n\n<script>alert(1)</script>\n![x](https://example.test/x)'}];
    return {...session};
  }
  if(path.endsWith('/messages')){messages.push({id:messages.length+1,role:'user',content:JSON.parse(options.body).message},{id:messages.length+2,role:'assistant',content:'已进一步分析'});return {...session};}
  if(path.endsWith('/cancel')){session.status='cancelled';return {ok:true};}
  if(path.startsWith('/api/agent/sessions/')&&path.includes('?after=')){
    const selectedID=path.split('/')[4].split('?')[0],selected=selectedID===id?session:sessions.find(row=>row.id===selectedID)||session;
    const after=Number(path.split('after=')[1]),source=selectedID===id?messages:[],batch=source.filter(m=>m.id>after).slice(0,2);
    return {session:{...selected},messages:batch,next_after:batch.at(-1)?.id||after,has_more:source.some(m=>m.id>(batch.at(-1)?.id||after)),active_job:null};
  }
  throw Error('Unexpected API '+path);
}};
vm.createContext(sandbox);vm.runInContext(fs.readFileSync('dist/agent.js','utf8'),sandbox);
const run=code=>vm.runInContext(code,sandbox),flush=()=>new Promise(resolve=>setImmediate(resolve));
(async()=>{
  run('agentControls()');assert(!element('generateReport').disabled);assert(element('generateHostReport').disabled);
  assert(element('hostAgentSourceHint').textContent.includes('添加宿主机目录'));
  run('setAgentConcurrency(0)');await run('generateDiskReport()');assert(element('agentError').textContent.includes('1–16'));assert.equal(calls.length,0);
  run('setAgentConcurrency(3)');assert.equal(element('reportConcurrency').value,3);
  await run('generateDiskReport()');
  assert.equal(calls.filter(c=>c.path==='/api/agent/reports').length,1);
  assert(element('agentDialog').open);assert(element('agentReports').innerHTML.includes('<table>'));assert(element('agentReports').innerHTML.includes('<strong>1 GiB</strong>'));
  assert(!element('agentReports').innerHTML.includes('<script>'));assert(!element('agentReports').innerHTML.includes('<img'));assert(element('agentReports').innerHTML.includes('&lt;script&gt;'));
  assert(element('agentActivityLog').innerHTML.includes('/data/&lt;unsafe&gt;'));assert(!element('downloadReport').disabled);assert(!element('agentFollowup').hidden);
  const count=run('agentView.messages.length');await run('readAgentSession()');assert.equal(run('agentView.messages.length'),count,'poll must not repeat messages');
  const group={id:90,role:'group_report',content:JSON.stringify({group_id:'',text:'### 第 1/3 组 · 4 个容器\n\n## 2. 存在争议\n\n分组模型权重结果 <script>bad()</script>'})};
  run('appendAgentMessages('+JSON.stringify([group])+')');
  assert(element('agentActivityLog').innerHTML.includes('第 1/3 组 · 4 个容器 · 查看结果'));
  assert(!element('agentActivityLog').innerHTML.includes('<script>'));
  assert(!element('agentReports').innerHTML.includes('分组模型权重结果'),'group results must not clutter final report');
  await run('postAgentAction("messages",{message:"继续查看缓存"})');assert(element('agentReports').innerHTML.includes('继续查看缓存'));assert(element('agentReports').innerHTML.includes('已进一步分析'));
  run('downloadAgentReport()');const exported=await download.text();assert(exported.includes('# 总报告'));assert(exported.includes('继续查看缓存'));assert(exported.includes(record));assert(!exported.includes('server report request'));
  assert(!exported.includes('分组模型权重结果'),'export only merged report and followups');
  const unsafe=run('reportMarkdown("```html\\n<img src=x onerror=alert(1)>\\n```\\n\\n| A | B |\\n| --- | --- |\\n| `/a\\\\|b` | 1 |")');assert(!unsafe.includes('<img'));assert(unsafe.includes('/a|b'));
  sandbox.platform.loaded='c'.repeat(32);run('renderAgentSession()');assert(element('agentReportSource').textContent.includes('不同'));sandbox.platform.loaded=record;
  session.status='running';sessions=[{...session}];const before=calls.filter(c=>c.path==='/api/agent/reports').length;await run('generateDiskReport()');assert.equal(calls.filter(c=>c.path==='/api/agent/reports').length,before,'resume active report instead of creating duplicate');assert(element('sendAgentQuestion').disabled);assert(!element('stopAgent').hidden);
  await run('postAgentAction("cancel",{})');assert(element('stopAgent').hidden);assert(!element('sendAgentQuestion').disabled);
  session.snapshot_id=null;await run('readAgentSession()');assert(element('sendAgentQuestion').disabled);assert(!element('downloadReport').disabled,'report remains exportable after record deletion');session.snapshot_id=record;
  run('window.AgentUI.reset()');assert.equal(element('agentReports').innerHTML,'');assert(!element('agentDialog').open);
  sessions=[];settings.model='';await run('generateDiskReport()');assert(element('agentError').textContent.includes('模型设置'));assert.equal(calls.filter(c=>c.path==='/api/agent/reports').length,before);settings.model='test';
  failure={path:'/api/agent/reports',message:'扫描记录已更新，请刷新'};await run('generateDiskReport()');assert(element('agentError').textContent.includes('扫描记录已更新'));assert(!element('generateReport').disabled);failure=null;
  hold={path:'/api/agent/reports'};const creating=run('generateDiskReport()');await flush();const n=calls.length;await run('generateDiskReport()');assert.equal(calls.length,n,'duplicate clicks must not post twice');run('window.AgentUI.reset()');hold.resolve(session);await creating;hold=null;assert.equal(run('agentView.session'),null,'creation response after logout must be discarded');assert.equal(element('agentReports').innerHTML,'');
  await run('selectAgentSession('+JSON.stringify(session)+')');
  hold={path:`/api/agent/sessions/${id}?after=${run('agentView.cursor')}`};const reading=run('readAgentSession()');run('window.AgentUI.reset()');hold.resolve({session,messages:[{id:50,role:'assistant',content:'private old response'}],next_after:50,has_more:false});await reading;hold=null;assert.equal(element('agentReports').innerHTML,'');
  await run('selectAgentSession('+JSON.stringify({...session,status:'running'})+')');
  const request={request_id:'r1',round:1,model:'test',protocol:'responses',context_items:2,context_bytes:2048,request_bytes:2200,context:[{role:'system',content:'system <unsafe>'},{role:'user',content:'初始问题'}],tools:[]};
  const trace=[{id:100,role:'model_request',content:JSON.stringify(request)},{id:101,role:'model_delta',content:JSON.stringify({request_id:'r1',deltas:[{kind:'summary',text:'公开摘要'},{kind:'text',text:'部分输出'}]})}];
  run('appendAgentMessages('+JSON.stringify(trace)+')');run('appendAgentMessages('+JSON.stringify(trace)+')');
  assert.equal(run('agentView.requests.get("r1").text'),'部分输出','duplicate events must not append text twice');
  assert(element('agentRequestSummaryText-100').innerHTML.includes('公开摘要'));assert(!element('agentActivityLog').innerHTML.includes('system &lt;unsafe&gt;'));assert(!element('agentActivityLog').innerHTML.includes('<unsafe>'));
  run('appendAgentMessages('+JSON.stringify([{id:102,role:'model_response',content:JSON.stringify({request_id:'r1',status:'cancelled',error:'请求停止',text:'',summary:'',usage:null,duration_ms:1500})}])+')');
  assert.equal(run('agentView.requests.get("r1").text'),'部分输出');assert(element('agentRequestState-100').textContent.includes('未完成'));assert(!element('agentActivityLog').innerHTML.includes('Token 用量'));
  run('appendAgentMessages('+JSON.stringify([{id:103,role:'model_request',content:JSON.stringify({...request,request_id:'interrupted'})},{id:104,role:'user',content:'中断后继续提问'}])+')');
  assert.equal(run('agentView.requests.get("interrupted").status'),'interrupted','followups must not revive unfinished old requests');
  run('agentView.session.status="running"');
  const push=events=>run('appendAgentMessages('+JSON.stringify(events)+')');
  const event=(id,role,data,tool_name)=>({id,role,content:JSON.stringify(data),tool_name});
  push([event(105,'model_request',{...request,request_id:'thinking',protocol:'completions'}),event(106,'model_delta',{request_id:'thinking',deltas:[{kind:'reasoning',text:'先检查目录。\n\n<script>bad()</script>'}]})]);
  assert(element('agentActivityLog').innerHTML.includes('<summary>完整思考</summary>'));
  assert(element('agentActivityLog').innerHTML.includes('<summary>思考摘要</summary>'));
  assert(element('agentRequestState-105').textContent.includes('正在思考'));
  assert(element('agentRequestSummaryText-105').innerHTML.includes('&lt;script&gt;'));
  assert(!element('agentRequestSummaryText-105').innerHTML.includes('<script>'));
  element('agentRequestSummary-105').open=true;
  push([event(107,'model_delta',{request_id:'thinking',deltas:[{kind:'reasoning',text:'\n再比较占用。'}]})]);
  assert(element('agentRequestSummary-105').open,'streaming must preserve expanded thinking');
  assert(element('agentRequestSummaryText-105').innerHTML.includes('再比较占用。'));
  push([event(108,'model_response',{request_id:'thinking',status:'cancelled',reasoning:''})]);
  assert(element('agentRequestSummaryText-105').innerHTML.includes('再比较占用。'),'cancelled reasoning must remain visible');
  push([event(109,'model_response',{request_id:'thinking',status:'completed',reasoning:'完整思考历史记录',text:'检查完成'})]);
  assert(element('agentRequestSummaryText-105').innerHTML.includes('完整思考历史记录'),'completed responses must restore full reasoning');
  push([event(110,'model_request',{...request,request_id:'structured'}),event(111,'model_delta',{request_id:'structured',deltas:[{kind:'text',text:'{"containers":['}]})]);
  assert.equal(element('agentRequestOutput-110').innerHTML,'','partial report JSON must never enter a bubble');
  assert(element('agentRequestState-110').textContent.includes('整理分析结果'));
  push([event(112,'model_response',{request_id:'structured',status:'completed',text:'{"containers":[]}'})]);
  assert(element('agentRequest-110').hidden,'completed structured responses leave no empty bubble');
  for(const text of ['{','[','`','``','```','```j','```json\n{"containers":'])assert.equal(run('agentProse('+JSON.stringify(text)+')'),'');
  assert.equal(run('agentProse("[提示] 已完成检查")'),'[提示] 已完成检查');
  run('agentView.session.status="cancelled"');assert.equal(run('agentStepStatus()'),'cancelled');
  run('agentView.session.status="running"');
  push([event(113,'model_request',{...request,request_id:'reply'}),event(114,'model_delta',{request_id:'reply',deltas:[{kind:'text',text:'唯一的一条回复'},{kind:'tool',index:0,name:'get_directory',arguments:'{"path":'}]})]);
  assert(element('agentRequestState-113').textContent.includes('准备读取目录明细'));
  assert(!element('agentRequestState-113').textContent.includes('{'));
  push([event(115,'model_response',{request_id:'reply',status:'completed',text:'唯一的一条回复'})]);
  assert(element('agentRequestState-113').hidden,'successful replies need no protocol completion label');
  const bubblesBefore=element('agentActivityLog').innerHTML;
  push([{id:116,role:'assistant',content:'唯一的一条回复'}]);
  assert.equal(element('agentActivityLog').innerHTML,bubblesBefore,'the persisted final answer must not duplicate its streamed bubble');
  push([event(117,'tool_start',{call_id:'failed',arguments:'{"path":"/data","limit":20}'},'get_directory'),event(118,'tool_end',{call_id:'failed',status:'failed',result:'{"error":"目录不可读 <unsafe>","debug":"raw tool dump"}',duration_ms:40})]);
  assert.equal(element('agentToolError-117').textContent,'目录不可读 <unsafe>');
  assert(element('agentToolState-117').textContent.includes('失败'));
  assert(!element('agentActivityLog').innerHTML.includes('raw tool dump'));
  const beforeEvidence=element('agentActivityLog').innerHTML;
  push([{id:119,role:'tool_result',tool_name:'get_overview',content:'{"private_evidence":123}'},{id:120,role:'note',content:'唯一的一条回复'}]);
  assert.equal(element('agentActivityLog').innerHTML,beforeEvidence,'preloaded evidence and duplicate notes are not conversation messages');
  const plan=event(130,'report_plan',{concurrency:2,groups:[{id:'group-1',number:1,containers:[{id:'c1',name:'worker <unsafe>'}]},{id:'group-2',number:2,containers:[{id:'c2',name:'second'}]},{id:'group-3',number:3,containers:[{id:'c3',name:'third'}]}]});
  push([plan,event(131,'group_state',{id:'group-1',status:'running'}),event(132,'model_request',{...request,request_id:'group-one',group_id:'group-1'})]);
  assert.equal(run('agentView.scope'),'group-1');assert(element('agentGroupList').innerHTML.includes('worker &lt;unsafe&gt;'));
  push([plan]);assert.equal(run('agentView.groups.get("group-1").status'),'running','replayed plan must not reset group state');
  assert(element('agentFollowup').hidden,'group view must not imply followups are sent to that independent context');
  element('agentActivityLog').scrollTop=123;run('selectAgentScope("group-2")');
  assert(!element('agentScopeEmpty').hidden);assert(element('agentScopeEmpty').textContent.includes('等待'));
  push([event(133,'group_state',{id:'group-1',status:'completed'}),event(134,'group_state',{id:'group-2',status:'running'}),event(135,'model_request',{...request,request_id:'group-two',group_id:'group-2'})]);
  assert.equal(run('agentView.scope'),'group-2');assert.equal(run('agentView.requests.get("group-two").scope'),'group-2');
  run('selectAgentScope("group-1")');assert.equal(element('agentActivityLog').scrollTop,123,'group scroll position should survive switching');
  run('agentSetTab("report")');element('agentActivityLog').scrollTop=0;run('selectAgentScope("group-1")');
  assert.equal(element('agentActivityLog').scrollTop,123,'report tab must not erase the group reading position');
  push([event(136,'model_delta',{request_id:'group-two',group_id:'group-2',deltas:[{kind:'text',text:'second agent reply'}]}),event(137,'group_state',{id:'group-2',status:'failed',error:'模型连接失败'})]);
  assert.equal(run('agentView.scope'),'group-1','updates to another group must not steal selection');
  assert.equal(run('agentRunningGroups().length'),0);
  run('agentView.session.status="failed";renderAgentSession()');
  assert.equal(run('agentGroupStatus(agentView.groups.get("group-1"))'),'completed');
  assert.equal(run('agentGroupStatus(agentView.groups.get("group-2"))'),'failed');
  assert.equal(run('agentGroupStatus(agentView.groups.get("group-3"))'),'not_started');
  push([{id:138,role:'user',content:'失败后继续追问'},event(139,'model_request',{...request,request_id:'followup'})]);
  assert.equal(run('agentView.requests.get("followup").scope'),'main','followup belongs to the overall conversation');
  run('agentView.session.status="running"');
  assert.equal(run('agentGroupStatus(agentView.groups.get("group-3"))'),'not_started','followup must not restart skipped groups');
  push([event(150,'model_response',{request_id:'group-two',group_id:'group-2',status:'failed',error:'模型连接失败'})]);
  run('selectAgentScope("group-2");agentView.session.status="failed";renderAgentSession()');
  assert(!element('agentRetry').hidden&&!element('agentRetry').disabled);
  run('selectAgentScope("group-1")');assert(!element('agentRetry').hidden,'batch retry stays available while viewing a completed agent');
  run('selectAgentScope("group-2");agentView.session.snapshot_id=null;agentControls()');
  assert(element('agentRetry').disabled,'deleted records cannot be retried');
  run('agentView.session.snapshot_id='+JSON.stringify(record)+';agentControls()');
  push([event(160,'model_request',{...request,request_id:'group-three-failed',group_id:'group-3'}),event(161,'model_response',{request_id:'group-three-failed',group_id:'group-3',status:'failed'}),event(162,'group_state',{id:'group-3',status:'failed'})]);
  assert(element('agentRetry').textContent.includes('2'),'button should show the number of failed agents');
  const retryPath=`/api/agent/sessions/${id}/retry`,reportsBeforeRetry=calls.filter(c=>c.path==='/api/agent/reports').length;
  hold={path:retryPath};
  const retrying=run('retryAgentGroups()');await flush();
  const posted=calls.length;await run('retryAgentGroups()');assert.equal(calls.length,posted,'double clicks cannot resend a retry');
  assert.deepEqual(JSON.parse(calls.at(-1).options.body),{requests:[{group_id:'group-2',request_id:'group-two'},{group_id:'group-3',request_id:'group-three-failed'}]});
  session.status='queued';hold.resolve({...session});await retrying;hold=null;
  assert.equal(run('agentView.scope'),'group-2','retry should keep the selected agent');
  assert.equal(run('agentView.groups.get("group-1").status'),'completed');
  assert.equal(calls.filter(c=>c.path==='/api/agent/reports').length,reportsBeforeRetry,'retry must not regenerate the full report');
  assert(element('agentRetry').disabled,'active retries disable resubmission');
  push([event(163,'group_state',{id:'group-3',status:'queued'}),event(151,'group_state',{id:'group-2',status:'running'}),event(152,'model_request',{...request,request_id:'group-two-retry',group_id:'group-2',round:3})]);
  assert(element('agentRetry').hidden,'an old failure must not stay retryable after a new request');
  push([event(153,'model_response',{request_id:'group-two-retry',group_id:'group-2',status:'failed'}),event(154,'group_state',{id:'group-2',status:'failed'})]);
  run('agentView.session.status="failed";renderAgentSession()');
  assert.equal(run('agentRetryRequests()[0].request_id'),'group-two-retry','retry must target the newest failure');
  assert(element('agentRetry').title.includes('第 3 轮'));
  run('agentView.session.status="running";$("agentDialog").showModal();connectAgentStream()');
  const staleStream=streams.at(-1);assert(staleStream.url.includes('/events?after='));run('window.AgentUI.reset()');assert(staleStream.closed);
  staleStream.listeners.session({data:JSON.stringify({session,messages:[{id:999,role:'user',content:'private after logout'}],next_after:999,has_more:false})});
  assert.equal(element('agentActivityLog').innerHTML,'','closed streams must not restore private content');
  sandbox.platform.user={role:'viewer'};const total=calls.length;run('agentControls()');await run('generateDiskReport()');await run('openAgentReports()');assert(element('generateReport').disabled);assert.equal(calls.length,total);
  sandbox.platform.user={role:'admin'};run('window.AgentUI.reset()');sessions=[];session.status='completed';session.snapshot_id=record;
  sandbox.snapshot.resources=[{path:'/srv',kinds:['host'],containers:[]}];
  run('setAgentConcurrency(5,"host")');assert.equal(element('hostReportConcurrency').value,5);assert.equal(element('reportConcurrency').value,3);
  await run('generateDiskReport("host")');assert.equal(run('agentView.reportScope'),'host');assert.equal(element('agentConcurrency').value,5);
  assert(element('agentQuestion').placeholder.includes('Host 扫描范围'));assert.equal(suggestionButtons[0].textContent,'重点目录');assert(suggestionButtons[0].dataset.agentQuestion.includes('Host 扫描范围'));
  assert.equal(JSON.parse(calls.filter(c=>c.path==='/api/agent/reports').at(-1).options.body).scope,'host');
  run('appendAgentMessages('+JSON.stringify([{id:200,role:'report_plan',content:JSON.stringify({scope:'host',concurrency:5,groups:[{id:'host-group',number:1,directories:[{path:'/srv/<private>',name:'srv'}]}]})}])+')');
  assert(element('agentGroupList').innerHTML.includes('/srv/&lt;private&gt;'));assert(element('agentGroupList').innerHTML.includes('1 个目录'));
  const containerHistory={id:'c'.repeat(32),title:'仅容器报告',report_scope:'container',status:'completed',snapshot_id:record,model:'test',created_at:1,updated_at:1};
  sessions.push(containerHistory,{id:'d'.repeat(32),title:'自定义会话',report_scope:'',status:'completed',created_at:1,updated_at:1});
  await run('loadAgentHistory()');
  assert(!element('agentHistory').innerHTML.includes('仅容器报告'),'Host 历史不能混入容器报告');
  await run('selectAgentReportScope("container")');
  assert.equal(run('agentView.reportScope'),'container');assert(element('agentHistory').innerHTML.includes('仅容器报告'));
  assert.equal(element('agentQuestion').placeholder,'例如：继续查看最大的可写层中有哪些数据集');assert.equal(suggestionButtons[0].textContent,'数据集与模型');assert(suggestionButtons[0].dataset.agentQuestion.includes('可写层'));
  assert(!element('agentHistory').innerHTML.includes('Host'),'容器历史不能混入 Host 报告');
  assert(!element('agentHistory').innerHTML.includes('自定义会话'),'自定义会话不能混入报告历史');
  console.log('Agent UI checks passed: selected-record reports, paging, Markdown escaping, followups, exports, progress/cancel, deleted records, configuration errors, duplicate clicks and stale responses after logout.');
})().catch(error=>{console.error(error);process.exitCode=1;});
