// State/render contract tests in a minimal DOM stub; not browser visual QA.
'use strict';
const assert = require('assert'), fs = require('fs'), vm = require('vm');
const elements = new Map();
function element(id) {
  if (!elements.has(id)) elements.set(id,{innerHTML:'',textContent:'',value:'',hidden:false,disabled:false,open:false,firstChild:{textContent:''},listeners:{},querySelector(){return {focus(){}};},classList:{toggle(){}},addEventListener(type,fn){this.listeners[type]=fn;},setAttribute(){},showModal(){this.open=true;},close(){this.open=false;},scrollIntoView(options){this.scrollCount=(this.scrollCount||0)+1;this.scrollOptions=options;}});
  return elements.get(id);
}
const documentListeners = {};
const sandbox = {console,setTimeout,clearTimeout,document:{getElementById:element,querySelectorAll:()=>[],addEventListener(type,fn){documentListeners[type]=fn;}},window:{addEventListener(){}}};
sandbox.renderTask=()=>{};
sandbox.platform=sandbox.window.platform || {user:null,jobs:[]};
vm.createContext(sandbox);
for (const path of ['dist/usage.js','dist/snapshot.js','dist/app.js']) vm.runInContext(fs.readFileSync(path,'utf8'),sandbox);
sandbox.sampleText = fs.readFileSync('tests/fixtures/snapshot.json','utf8');
const run = code => vm.runInContext(code,sandbox);
run('var sample=JSON.parse(sampleText);load(sample,"test")');
assert.equal(element('sourceBadge').textContent,'test');
run("sample.filesystems.push({device:'virtual',mount:'/run',fs:'tmpfs',total:50*1024**3,used:0,available:50*1024**3,scanned:0,unexplained:0});load(sample,'test')");
assert(element('storageOverview').innerHTML.includes(`可用 ${run('fmt(sample.filesystems[0].available)')}`));
assert(!element('storageOverview').innerHTML.includes('/run'));
assert(element('diskAccounting').innerHTML.includes('/run'),'virtual filesystem accounting remains visible');
run('sample.filesystems.pop();load(sample,"test")');
assert.equal(element('containerCount').textContent,3);
assert(element('ownerRanking').innerHTML.includes('96 GiB'));
assert(element('tableBody').innerHTML.indexOf('yuuka-train')<element('tableBody').innerHTML.indexOf('lin-notebook'));
run('filterOwner("lin")');assert(element('tableBody').innerHTML.includes('lin-notebook'));assert(!element('tableBody').innerHTML.includes('yuuka-train'));
run('clearFilters();stateFilter="stopped";renderContainers()');assert(element('tableBody').innerHTML.includes('chen-inference'));assert(!element('tableBody').innerHTML.includes('yuuka-train'));
run('clearFilters();query="pytorch";sortOrder="exclusive-asc";renderContainers()');assert(element('tableBody').innerHTML.indexOf('chen-inference')<element('tableBody').innerHTML.indexOf('yuuka-train'));
run('clearFilters();select("container",snapshot.containers[0])');assert(element('containerDialog').open);assert(element('storageSources').innerHTML.includes('/models'));assert(element('detail').innerHTML.includes('Docker 逻辑大小'));
run('snapshot.containers[0].owner="lin";rebuildUsage()');assert(Math.abs(run('usage.owners.get("lin").bytes')-(96+48+348)*1024**3)<=4);assert(!element('ownerRanking').innerHTML.includes('yuuka</span>'));
assert.throws(()=>run('load({schema_version:6},"bad")'));
assert.throws(()=>run('validate({...sample,tree:{...sample.tree,allocated:-1}})'));
run('clearFilters();sample.containers[0].name="<img src=x onerror=alert(1)>";load(sample,"test")');assert(!element('tableBody').innerHTML.includes('<img'));assert(element('tableBody').innerHTML.includes('&lt;img'));
run('snapshot.containers[0].upper_path=null;snapshot.containers[0].writable_layer={allocated:null,apparent:null,status:"unavailable",permission_denied:false};rebuildUsage();select("container",snapshot.containers[0])');assert(element('detail').innerHTML.includes('未知'));assert(element('detail').innerHTML.includes('部分统计'));
run('query="nonexistent";renderContainers()');assert(element('tableBody').innerHTML.includes('没有匹配的容器'));
run('clearFilters();sample.containers=Array.from({length:61},(_,i)=>({...sample.containers[1],id:String(i),name:"container-"+i}));load(sample,"test")');
assert.equal(element('pageNumber').textContent,'1 / 3');assert.equal((element('tableBody').innerHTML.match(/<tr>/g)||[]).length,25);
run('tablePage=2;renderContainers()');assert.equal((element('tableBody').innerHTML.match(/<tr>/g)||[]).length,11);assert(element('nextPage').disabled);
run('filterOwner("nobody")');assert.equal(element('pageNumber').textContent,'1 / 1');
// Physical layer allocation and Docker logical size are separate measurements.
run(`sample=JSON.parse(sampleText);sample.containers[0].writable_layer={allocated:null,apparent:null,status:'unreadable',permission_denied:true,reason:'权限不足 <script>'};sample.containers[0].size_rw=3*1024**4;sample.containers[1].writable_layer={allocated:0,apparent:0,status:'complete',permission_denied:false};sample.filesystems[0].scanned=123;sample.filesystems[0].unexplained=-456;clearFilters();load(sample,'new');sortOrder='writable-desc';renderContainers()`);
assert(element('tableBody').innerHTML.includes('权限不足'));
assert(element('tableBody').innerHTML.includes('Docker 逻辑 3 TiB'));
assert(!element('tableBody').innerHTML.includes('<script>'));
assert(element('tableBody').innerHTML.indexOf('lin-notebook')<element('tableBody').innerHTML.indexOf('yuuka-train'),'known zero must sort before unreadable layers');
assert(element('diskAccounting').innerHTML.includes('扫描超出 456 B'));
assert(element('diskAccounting').innerHTML.includes('123 B'));
run(`sortOrder='logical-desc';renderContainers();select('container',snapshot.containers[0])`);
assert(element('tableBody').innerHTML.indexOf('yuuka-train')<element('tableBody').innerHTML.indexOf('lin-notebook'));
assert(element('detail').innerHTML.includes('权限不足 &lt;script&gt;'));
assert(run('usage.exclusive')<1024**4,'logical size must not inflate physical totals');
assert.throws(()=>run(`validate({...sample,containers:[{...sample.containers[0],writable_layer:{status:'complete',allocated:-1}}]})`));
run(`sample=JSON.parse(sampleText);const upper=sample.containers[0].upper_path;const todo=[sample.tree];while(todo.length){const n=todo.pop();if(n.path===upper){n.children=[{...n,path:upper+'/root',name:'root',children:[]}];break;}todo.push(...n.children);}sample.scan={...sample.scan,backend:'docker'};clearFilters();load(sample,'helper');select('container',snapshot.containers[0])`);
assert(element('explorerContent').innerHTML.includes('可写层目录明细'));
assert(element('directoryMap').innerHTML.includes('>root</span>'));
assert(element('diskAccounting').innerHTML.includes('Docker 只读辅助容器'));
console.log('UI checks passed: container-first display, owner ranking/filtering, state/search/sort, details, recomputed ownership, escaping, unknown values, empty states and pagination.');

const click = dataset => documentListeners.click({target:{closest:()=>({dataset})}});
run(`sample=JSON.parse(sampleText);clearFilters();load(sample,'visual');`);
assert(element('storageOverview').innerHTML.includes('磁盘空间分布'));
assert(element('storageOverview').innerHTML.includes('容器共享'));
assert(element('storageOverview').innerHTML.includes('data-container='));
assert(!element('containerChart').hidden);assert(element('containerTable').hidden);
assert(element('containerChart').innerHTML.includes('yuuka-train'));
click({containerView:'table'});assert(element('containerChart').hidden);assert(!element('containerTable').hidden);
click({containerView:'chart'});
run(`
var g=1024**3;
var makeEntry=(path,bytes,children=[],extra={})=>({path,name:path.split('/').pop(),kind:'directory',allocated:bytes,apparent:bytes,files:1,errors:0,children,...extra});
var root=usage.inspect(sample.containers[0].upper_path).node;
root.children=[makeEntry(root.path+'/root',70*g,[makeEntry(root.path+'/root/.cache',50*g,[makeEntry(root.path+'/root/.cache/blobs',40*g,[],{kind:'file'})]),makeEntry(root.path+'/root/secrets',0,[],{kind:'unreadable',errors:1})]),makeEntry(root.path+'/workspace',20*g),makeEntry(root.path+'/loop',0,[],{kind:'reference',reference:root.path})];
root.omitted_entries=12;
load(sample,'nested');select('container',snapshot.containers[0]);
`);
assert(element('directoryMap').innerHTML.includes('data-storage-entry'));
const indexOf = name => run(`explorer.entries.findIndex(e=>e.name===${JSON.stringify(name)})`);
click({storageEntry:String(indexOf('root'))});
assert.equal(run('explorer.trail.length'),2);
assert(element('explorerContent').innerHTML.includes('容器内：/root'));
click({storageEntry:String(indexOf('secrets'))});
assert(element('directorySelection').innerHTML.includes('大小未知'));
assert(element('directorySelection').innerHTML.includes('实际占用 未知'));
click({storageEntry:String(indexOf('.cache'))});
assert.equal(run('explorer.trail.length'),3);
assert(element('explorerContent').innerHTML.includes('容器内：/root/.cache'));
click({storageEntry:String(indexOf('blobs'))});
assert.equal(run('explorer.trail.length'),3,'files should show details without navigating');
assert(element('directorySelection').innerHTML.includes('40 GiB'));
click({storageUp:''});assert.equal(run('explorer.trail.length'),2);
click({storageCrumb:'0'});assert.equal(run('explorer.trail.length'),1);
click({storageEntry:String(indexOf('loop'))});assert.equal(run('explorer.trail.length'),1,'cyclic directory references must not grow history');
assert(element('directorySelection').innerHTML.includes('引用目标'));
element('mapSearch').listeners.input({target:{value:'workspace'}});
assert(element('directoryMap').innerHTML.includes('>workspace</span>'));
assert(!element('directoryMap').innerHTML.includes('>root</span>'));
click({storageSource:'1'});
assert.equal(run('explorer.query'),'');
assert(element('explorerContent').innerHTML.includes('容器内：/models'));
assert(element('directoryMap').innerHTML.includes('DeepSeek-R1'));
run(`sample.containers[0].mounts.push({type:'tmpfs',source:null,destination:'/memory',rw:true});load(sample,'new');select('container',snapshot.containers[0]);`);
click({storageSource:'3'});assert(element('explorerContent').innerHTML.includes('暂无可读取的目录明细'));
assert(element('explorerContent').innerHTML.includes('用量为未知'));
// Large folders remain fully accessible while maps stay bounded and searches escape text.
run(`root=usage.inspect(snapshot.containers[0].upper_path).node;root.children=Array.from({length:121},(_,i)=>makeEntry(root.path+'/file-'+i,121-i,[],{kind:'file'}));root.children[0].path=root.path+'/<img src=x>';load(snapshot,'many');select('container',snapshot.containers[0]);`);
assert((element('directoryMap').innerHTML.match(/class="map-tile/g)||[]).length<=48);
assert(element('directoryMap').innerHTML.includes('data-map-group'));
click({mapGroup:''});click({mapGroup:''});
assert(element('directoryMap').innerHTML.includes('file-120'));
assert(element('mapGroupNavigation').innerHTML.includes('返回全部区块'));
element('mapSearch').listeners.input({target:{value:'<img'}});
assert(!element('directoryMap').innerHTML.includes('<img'));
assert(element('directoryMap').innerHTML.includes('&lt;img'));
assert.equal(run('explorer.page'),0);
run('rebuildUsage()');assert.equal(run('explorer.query'),'<img','owner edits should preserve directory navigation');
run('load(snapshot,"refresh")');assert.equal(run('explorer.trail.length'),1,'new snapshots must not retain stale directory nodes');
element('containerDialog').close();run('select("container",snapshot.containers[0])');
element('containerDialog').listeners.close();assert(run('explorer'),'a queued close event must not clear a reopened explorer');
element('containerDialog').close();element('containerDialog').listeners.close();assert.equal(run('explorer'),null);
console.log('Explorer UI checks passed: chart/table switching, directory drilldown, breadcrumbs/back, file inspection, unknown paths, cyclic references, source switching, searching, pagination and refresh.');

// Historical pending bytes are always expanded at their own directory.
run(`
sample=JSON.parse(sampleText);sample.job_id='live-job';sample.revision=0;
platform={user:{role:'admin'},jobs:[]};
root=Usage.build(sample).inspect(sample.containers[0].upper_path).node;
var lazyPath=root.path+'/lazy';
root.children=[makeEntry(lazyPath,1024,[],{omitted_entries:10})];
load(sample,'saved');select('container',snapshot.containers[0]);
openDirectoryEntry(explorer.entries.findIndex(e=>e.path===lazyPath));
var requested=[];function expandLeaf(path){requested.push(path);}
`);
click({storageEntry:String(run(`explorer.entries.findIndex(e=>e.kind==='residual')`))});
assert.equal(run('requested[0]'),run('lazyPath'),'clicking the gray block scans its own directory directly');
run(`
var next=JSON.parse(JSON.stringify(snapshot)),leaf=Usage.build(next).nodes.get(lazyPath);
leaf.omitted_entries=0;leaf.scanning=true;
leaf.children=[makeEntry(lazyPath+'/MNIST-v2',512,[],{omitted_entries:4})];
next.revision=1;explorer.query='MNIST';explorer.page=0;load(next,'updated',Usage.build(next),true);
`);
assert.equal(run('explorer.trail[explorer.trail.length-1].path'),run('lazyPath'));
assert.equal(run('explorer.query'),'MNIST');
assert(element('directoryMap').innerHTML.includes('MNIST-v2'));
run("explorer.query='';renderDirectoryMap()");
assert(element('directoryMap').innerHTML.includes('子目录待分析的历史占用'));
assert(!element('explorerContent').innerHTML.includes('data-expand-path'));
assert(!element('directorySelection').innerHTML.includes('选择子目录'));
const before=element('directorySelection').scrollCount;
run('refreshDirectoryScan();refreshDirectoryScan();load(snapshot,"updated",Usage.build(snapshot),true)');
assert.equal(element('directorySelection').scrollCount,before,'live updates never scroll to the inspector');
run(`platform.user.role='viewer';refreshDirectoryScan()`);
assert(!element('directorySelection').innerHTML.includes('data-expand-path'));
assert(element('directoryStatus').innerHTML.includes('管理员'));
console.log('Live explorer checks passed: direct gray-block scanning, measured child tiles, preserved filters and scroll, viewer permissions.');
